# Generated by Django 5.1.6 on 2025-02-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="order_quantity",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
