# Generated by Django 5.1.6 on 2025-02-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_product_height_product_width"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
