# Generated by Django 5.1.6 on 2025-03-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_product_same_author_products_alter_product_height_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="배너 제목", max_length=100)),
                (
                    "image_url",
                    models.CharField(help_text="Firebase 이미지 URL", max_length=500),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="배너 정렬 순서"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
